name: Build Chiiugo Client App
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: App Version
        type: string
      os:
        required: true
        type: choice
        description: Runner
        options:
          - windows-latest
          - ubuntu-latest
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      os:
        required: true
        type: string
permissions:
  contents: read
env:
  version: ${{ inputs.version || '0.0.0' }}
jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./client-app/gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: superReleaseBuild -PappVersion=${{ env.version }}
          build-root-directory: client-app/
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.os }}-package
          path: |
            client-app/build/compose/binaries/main-release/*/*.*
            !client-app/build/compose/binaries/main-release/*/*.app
            client-app/build/compose/jars/*.jar
          if-no-files-found: error